import type { Question } from "./questions";

// 24 HARD (level-3) questions raising the ceiling of the four structural families
// (kind-category, part-whole, tool-function, degree) to real Upper-SSAT vocabulary.
// Every stem carries an unknown word + gloss; drilling these IS vocab acquisition.
// Generated by the lesson factory, supervisor-validated. Solvability Law: the
// back-solve + elimination path always works even when the stem word is unknown.
export const HARD_QUESTIONS: Question[] = [
  {
    id: "H4-01",
    family: "kind-category",
    stem: "ELEGY : POEM",
    bridge: "An elegy is a kind of poem.",
    gloss: "An ELEGY is a sad poem written to mourn someone who has died.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "WALTZ : DANCE",
        why: "Fits: a waltz is a kind of dance — one clean survivor.",
      },
      {
        label: "B",
        pair: "POEM : STANZA",
        why: "Part instead of whole (and flipped) — a stanza is a piece of a poem, not a kind of stanza.",
      },
      {
        label: "C",
        pair: "AUTHOR : NOVEL",
        why: "Same topic, wrong bridge — a person and what they write, not a kind of anything.",
      },
      {
        label: "D",
        pair: "LIBRARY : BOOK",
        why: "Same topic, wrong bridge — books belong in a library; a library is not a kind of book.",
      },
      {
        label: "E",
        pair: "DIRGE : FUNERAL",
        why: "Same topic, wrong bridge — a dirge is sung AT a funeral, not a kind of funeral.",
      },
    ],
  },
  {
    id: "H4-02",
    family: "kind-category",
    stem: "SCHOONER : SHIP",
    bridge: "A schooner is a kind of ship.",
    gloss: "A SCHOONER is a sailing ship with two or more tall masts.",
    correct: "A",
    choices: [
      { label: "A", pair: "SEDAN : CAR", why: "Fits: a sedan is a kind of car." },
      {
        label: "B",
        pair: "ENGINE : TRUCK",
        why: "Part instead of whole — an engine is a part of a truck, not a kind of truck.",
      },
      {
        label: "C",
        pair: "HARBOR : BOAT",
        why: "Same topic, wrong bridge — a harbor is where boats stay, not a kind of boat.",
      },
      {
        label: "D",
        pair: "VEHICLE : BICYCLE",
        why: "Flipped pair — a bicycle is a kind of vehicle; the order is backwards.",
      },
      {
        label: "E",
        pair: "SAILOR : SEA",
        why: "Same topic, wrong bridge — a person and the place they work.",
      },
    ],
  },
  {
    id: "H4-03",
    family: "kind-category",
    stem: "MAZURKA : DANCE",
    bridge: "A mazurka is a kind of dance.",
    gloss: "A MAZURKA is a lively Polish folk dance.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "SONATA : COMPOSITION",
        why: "Fits: a sonata is a kind of musical composition.",
      },
      {
        label: "B",
        pair: "BALLERINA : BALLET",
        why: "Same topic, wrong bridge — a dancer and the dance she performs, not a kind of ballet.",
      },
      {
        label: "C",
        pair: "DANCE : TANGO",
        why: "Flipped pair — a tango is a kind of dance; the order is backwards.",
      },
      {
        label: "D",
        pair: "CONDUCTOR : BATON",
        why: "Same topic, wrong bridge — a person and the tool they use.",
      },
      {
        label: "E",
        pair: "MELODY : SONG",
        why: "Part instead of whole — a melody is a part of a song, not a kind of song.",
      },
    ],
  },
  {
    id: "H4-04",
    family: "kind-category",
    stem: "CUTLASS : SWORD",
    bridge: "A cutlass is a kind of sword.",
    gloss: "A CUTLASS is a short, curved sword once carried by sailors and pirates.",
    correct: "B",
    choices: [
      {
        label: "A",
        pair: "DAGGER : STAB",
        why: "Same topic, wrong bridge — that's what a dagger is used to do, not what it is a kind of.",
      },
      { label: "B", pair: "MUSKET : FIREARM", why: "Fits: a musket is a kind of firearm." },
      {
        label: "C",
        pair: "BLADE : KNIFE",
        why: "Part instead of whole — a blade is a part of a knife, not a kind of knife.",
      },
      {
        label: "D",
        pair: "WEAPON : SPEAR",
        why: "Flipped pair — a spear is a kind of weapon; the order is backwards.",
      },
      {
        label: "E",
        pair: "SHEATH : SWORD",
        why: "Same topic, wrong bridge — a sheath holds a sword; it is not a kind of sword.",
      },
    ],
  },
  {
    id: "H4-05",
    family: "kind-category",
    stem: "TARN : LAKE",
    bridge: "A tarn is a kind of lake.",
    gloss: "A TARN is a small lake high up in the mountains.",
    correct: "C",
    choices: [
      {
        label: "A",
        pair: "GEYSER : ERUPT",
        why: "Same topic (water), wrong bridge — that's what a geyser does, not a category it belongs to.",
      },
      {
        label: "B",
        pair: "RIVER : DELTA",
        why: "Part instead of whole (and flipped) — a delta is a part of a river's end, not a kind of river.",
      },
      {
        label: "C",
        pair: "FJORD : INLET",
        why: "Fits: a fjord is a kind of inlet — a narrow arm of sea between cliffs.",
      },
      {
        label: "D",
        pair: "OCEAN : BAY",
        why: "Flipped pair — a bay is a smaller piece of ocean; the order is backwards.",
      },
      {
        label: "E",
        pair: "SHORE : SWIM",
        why: "Same topic, wrong bridge — a place and an activity, not a kind of anything.",
      },
    ],
  },
  {
    id: "H4-06",
    family: "kind-category",
    stem: "ADAGE : SAYING",
    bridge: "An adage is a kind of saying.",
    gloss: "An ADAGE is a short, wise old saying, like 'Look before you leap.'",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "LIMERICK : VERSE",
        why: "Fits: a limerick is a kind of verse — a funny five-line poem.",
      },
      {
        label: "B",
        pair: "WORD : SENTENCE",
        why: "Part instead of whole — a word is a piece of a sentence, not a kind of sentence.",
      },
      {
        label: "C",
        pair: "SPEECH : ORATOR",
        why: "Same topic, wrong bridge (and flipped) — an orator is the person who gives the speech.",
      },
      {
        label: "D",
        pair: "MOTTO : SHIELD",
        why: "Same topic, wrong bridge — a motto may be written on a shield, but it isn't a kind of shield.",
      },
      {
        label: "E",
        pair: "LANGUAGE : DIALECT",
        why: "Flipped pair — a dialect is a kind of language; the order is backwards.",
      },
    ],
  },
  {
    id: "H4-07",
    family: "part-whole",
    stem: "HILT : SWORD",
    bridge: "A hilt is the part of a sword that you grip.",
    gloss: "The HILT is the handle of a sword.",
    correct: "A",
    choices: [
      { label: "A", pair: "TRIGGER : RIFLE", why: "Fits: a trigger is a part of a rifle." },
      {
        label: "B",
        pair: "SWORD : DUEL",
        why: "Same topic, wrong bridge — a sword is used IN a duel; it isn't a part of one.",
      },
      {
        label: "C",
        pair: "KNIFE : CUT",
        why: "Wrong bridge — that's what a knife is used to do, not a part of anything.",
      },
      {
        label: "D",
        pair: "ARROW : QUIVER",
        why: "Same topic, wrong bridge — an arrow is stored in a quiver; stored-in is not part-of.",
      },
      {
        label: "E",
        pair: "CANNON : CANNONBALL",
        why: "Same topic, wrong bridge — a cannon fires a cannonball; the ball is not a part of the cannon.",
      },
    ],
  },
  {
    id: "H4-08",
    family: "part-whole",
    stem: "TINE : FORK",
    bridge: "A tine is the part of a fork that spears the food.",
    gloss: "A TINE is one of the pointed prongs on the end of a fork.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "BRISTLE : BRUSH",
        why: "Fits: a bristle is one of the small parts of a brush.",
      },
      {
        label: "B",
        pair: "FORK : SPOON",
        why: "Same topic, wrong bridge — two utensils side by side; neither is part of the other.",
      },
      {
        label: "C",
        pair: "PLATE : TABLE",
        why: "Same topic, wrong bridge — a plate sits ON a table; it is not a part of it.",
      },
      {
        label: "D",
        pair: "HANDLE : GRIP",
        why: "Wrong bridge — a handle is used to grip; that's a job, not a whole it belongs to.",
      },
      {
        label: "E",
        pair: "TEAPOT : SPOUT",
        why: "Flipped pair — the spout is part of the teapot; the order is backwards.",
      },
    ],
  },
  {
    id: "H4-09",
    family: "part-whole",
    stem: "CORNEA : EYE",
    bridge: "The cornea is the part of the eye at the very front.",
    gloss: "The CORNEA is the clear front layer of the eye that light passes through.",
    correct: "C",
    choices: [
      {
        label: "A",
        pair: "EAR : SOUND",
        why: "Same topic, wrong bridge — an organ and what it senses, not a part and its whole.",
      },
      {
        label: "B",
        pair: "RETINA : SEE",
        why: "Same topic, wrong bridge — pairs an eye part with a job, not with the whole it belongs to.",
      },
      {
        label: "C",
        pair: "VENTRICLE : HEART",
        why: "Fits: a ventricle is a part of the heart — one of its pumping chambers.",
      },
      {
        label: "D",
        pair: "SKELETON : BONE",
        why: "Flipped pair — a bone is part of the skeleton; the order is backwards.",
      },
      {
        label: "E",
        pair: "LUNG : BREATHE",
        why: "Wrong bridge — that's what a lung is used to do, not a whole it is part of.",
      },
    ],
  },
  {
    id: "H4-10",
    family: "part-whole",
    stem: "FRET : GUITAR",
    bridge: "A fret is the part of a guitar that marks where fingers press.",
    gloss: "A FRET is one of the thin metal ridges across a guitar's neck.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "REED : CLARINET",
        why: "Fits: a reed is a part of a clarinet — the thin piece that vibrates to make sound.",
      },
      {
        label: "B",
        pair: "GUITARIST : STRUM",
        why: "Same topic, wrong bridge — a person and their action, not a part and its whole.",
      },
      {
        label: "C",
        pair: "PIANO : INSTRUMENT",
        why: "Wrong bridge — a piano is a KIND of instrument, not a part of one.",
      },
      {
        label: "D",
        pair: "DRUM : BEAT",
        why: "Wrong bridge — a drum is used to beat out rhythm; that's a job, not a part.",
      },
      {
        label: "E",
        pair: "ORCHESTRA : CELLO",
        why: "Flipped pair — the cello is part of the orchestra; the order is backwards.",
      },
    ],
  },
  {
    id: "H4-11",
    family: "part-whole",
    stem: "CHASSIS : AUTOMOBILE",
    bridge: "The chassis is the part of an automobile that everything else is built on.",
    gloss: "The CHASSIS is the base frame a car is built on top of.",
    correct: "C",
    choices: [
      {
        label: "A",
        pair: "AXLE : ROTATE",
        why: "Same topic, wrong bridge — a car part paired with what it does, not with its whole.",
      },
      {
        label: "B",
        pair: "GARAGE : CAR",
        why: "Same topic, wrong bridge — a car parks in a garage; the garage is not a part of the car.",
      },
      {
        label: "C",
        pair: "HULL : BOAT",
        why: "Fits: the hull is the part of a boat that forms its body.",
      },
      {
        label: "D",
        pair: "CAR : SEDAN",
        why: "Wrong bridge (and flipped) — a sedan is a kind of car, not a part of one.",
      },
      {
        label: "E",
        pair: "ENGINE : FUEL",
        why: "Same topic, wrong bridge — an engine burns fuel; fuel is not the whole it belongs to.",
      },
    ],
  },
  {
    id: "H4-12",
    family: "part-whole",
    stem: "VERTEBRA : SPINE",
    bridge: "A vertebra is one of the small pieces that make up a spine.",
    gloss: "A VERTEBRA is one of the little bones stacked up to form your spine (backbone).",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "LINK : CHAIN",
        why: "Fits: a link is one of the small repeating pieces that make up a chain.",
      },
      {
        label: "B",
        pair: "SKULL : BRAIN",
        why: "Same topic, wrong bridge — the skull protects the brain; it is not a piece of it.",
      },
      {
        label: "C",
        pair: "STAIRCASE : STEP",
        why: "Flipped pair — a step is part of a staircase; the order is backwards.",
      },
      {
        label: "D",
        pair: "CAST : ARM",
        why: "Same topic, wrong bridge — a cast goes AROUND an arm; it is not a part of it.",
      },
      {
        label: "E",
        pair: "MUSCLE : FLEX",
        why: "Wrong bridge — that's what a muscle does, not a whole it is part of.",
      },
    ],
  },
  {
    id: "H4-13",
    family: "tool-function",
    stem: "AWL : PIERCE",
    bridge: "An awl is a tool used to pierce.",
    gloss:
      "An AWL is a pointed tool for poking small holes in leather or wood; to PIERCE is to poke through.",
    correct: "A",
    choices: [
      { label: "A", pair: "LADLE : SCOOP", why: "Fits: a ladle is a tool used to scoop." },
      {
        label: "B",
        pair: "NEEDLE : THREAD",
        why: "Same topic, wrong bridge — a needle is paired with its partner item, not with its job.",
      },
      {
        label: "C",
        pair: "HAMMER : NAIL",
        why: "Wrong bridge — a tool and the thing it hits, not the action it performs.",
      },
      {
        label: "D",
        pair: "PIERCE : DRILL",
        why: "Flipped pair — the action comes first; a drill is used to pierce, so the order is backwards.",
      },
      {
        label: "E",
        pair: "SAW : WOOD",
        why: "Wrong bridge — a tool and its material, not the action it is used for.",
      },
    ],
  },
  {
    id: "H4-14",
    family: "tool-function",
    stem: "LATHE : SHAPE",
    bridge: "A lathe is a tool used to shape.",
    gloss: "A LATHE is a machine that spins wood or metal so it can be shaped smooth and round.",
    correct: "A",
    choices: [
      { label: "A", pair: "LOOM : WEAVE", why: "Fits: a loom is a tool used to weave cloth." },
      {
        label: "B",
        pair: "SAWDUST : CARPENTER",
        why: "Same topic, wrong bridge — a leftover and a worker, not a tool and its job.",
      },
      {
        label: "C",
        pair: "WRENCH : PLUMBER",
        why: "Wrong bridge — a tool and the person who uses it, not the action it performs.",
      },
      {
        label: "D",
        pair: "CLAY : MOLD",
        why: "Flipped roles — clay is the material that GETS molded, not the tool doing it.",
      },
      {
        label: "E",
        pair: "ANVIL : IRON",
        why: "Wrong bridge — a tool and its material, not the action it is used for.",
      },
    ],
  },
  {
    id: "H4-15",
    family: "tool-function",
    stem: "PESTLE : GRIND",
    bridge: "A pestle is a tool used to grind.",
    gloss:
      "A PESTLE is a club-shaped tool used with a heavy bowl (a mortar) to crush things into powder.",
    correct: "B",
    choices: [
      {
        label: "A",
        pair: "MORTAR : BOWL",
        why: "Same topic, wrong bridge — a mortar IS the bowl; two names for similar things, no action.",
      },
      { label: "B", pair: "SIEVE : SIFT", why: "Fits: a sieve is a tool used to sift." },
      {
        label: "C",
        pair: "KITCHEN : COOK",
        why: "Wrong bridge — a place where cooking happens, not a tool that performs it.",
      },
      {
        label: "D",
        pair: "GRIND : CRUSH",
        why: "Wrong bridge — two similar actions with no tool at all.",
      },
      {
        label: "E",
        pair: "POWDER : PEPPER",
        why: "Same topic, wrong bridge — the result and a substance, not a tool and its job.",
      },
    ],
  },
  {
    id: "H4-16",
    family: "tool-function",
    stem: "SICKLE : REAP",
    bridge: "A sickle is a tool used to reap.",
    gloss: "A SICKLE is a curved blade for cutting grain; to REAP is to cut and gather crops.",
    correct: "B",
    choices: [
      {
        label: "A",
        pair: "PLOW : FARMER",
        why: "Wrong bridge — a tool and the person who uses it, not the action it performs.",
      },
      {
        label: "B",
        pair: "SHEARS : PRUNE",
        why: "Fits: shears are a tool used to prune (trim plants).",
      },
      {
        label: "C",
        pair: "WHEAT : HARVEST",
        why: "Flipped roles — wheat is the crop that GETS harvested, not the tool doing it.",
      },
      {
        label: "D",
        pair: "SCYTHE : SICKLE",
        why: "Same topic, wrong bridge — two similar cutting tools; neither is the other's job.",
      },
      {
        label: "E",
        pair: "FIELD : FURROW",
        why: "Same topic, wrong bridge — a place and a groove in it, not a tool and its action.",
      },
    ],
  },
  {
    id: "H4-17",
    family: "tool-function",
    stem: "WINCH : HOIST",
    bridge: "A winch is a tool used to hoist.",
    gloss:
      "A WINCH is a machine with a turning drum and cable for pulling; to HOIST is to lift something heavy.",
    correct: "A",
    choices: [
      { label: "A", pair: "LEVER : PRY", why: "Fits: a lever is a tool used to pry things loose." },
      {
        label: "B",
        pair: "CARGO : LIFT",
        why: "Flipped roles — cargo is the load that GETS lifted, not the tool doing the lifting.",
      },
      {
        label: "C",
        pair: "PULLEY : ROPE",
        why: "Same topic, wrong bridge — a tool and the rope that runs through it, not its action.",
      },
      {
        label: "D",
        pair: "ELEVATOR : BUILDING",
        why: "Same topic, wrong bridge — a thing and the place it belongs, not a tool and its job.",
      },
      { label: "E", pair: "DROP : RAISE", why: "Wrong bridge — opposites, with no tool at all." },
    ],
  },
  {
    id: "H4-18",
    family: "tool-function",
    stem: "CALIPERS : MEASURE",
    bridge: "Calipers are a tool used to measure.",
    gloss: "CALIPERS are a tool with two hinged arms for measuring how thick or wide something is.",
    correct: "B",
    choices: [
      {
        label: "A",
        pair: "RULER : STRAIGHT",
        why: "Same topic, wrong bridge — describes what a ruler IS, not the action it is used for.",
      },
      {
        label: "B",
        pair: "THERMOMETER : GAUGE",
        why: "Fits: a thermometer is a tool used to gauge (measure) temperature.",
      },
      {
        label: "C",
        pair: "INCH : YARD",
        why: "Same topic, wrong bridge — two units of measurement, no tool and no action.",
      },
      {
        label: "D",
        pair: "SCALE : WEIGHT",
        why: "Same topic, wrong bridge — pairs the tool with the THING measured, not the action of measuring.",
      },
      {
        label: "E",
        pair: "MEASURE : ESTIMATE",
        why: "Wrong bridge — two similar actions with no tool at all.",
      },
    ],
  },
  {
    id: "H4-19",
    family: "degree",
    stem: "GALE : BREEZE",
    bridge: "A gale is a stronger version of a breeze.",
    gloss: "A GALE is a very strong, roaring wind; a BREEZE is a soft, gentle one.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "BLIZZARD : FLURRY",
        why: "Fits: a blizzard is a stronger version of a flurry — heavy snow versus a light dusting.",
      },
      {
        label: "B",
        pair: "WIND : WEATHER",
        why: "Same topic, wrong bridge — wind is a kind of weather, not a stronger version of it.",
      },
      {
        label: "C",
        pair: "DRIZZLE : DELUGE",
        why: "Flipped pair — a deluge is the stronger one; the order is backwards.",
      },
      {
        label: "D",
        pair: "KITE : SOAR",
        why: "Same topic, wrong bridge — a thing and what it does in the wind, no strength ladder.",
      },
      {
        label: "E",
        pair: "HURRICANE : DAMAGE",
        why: "Wrong bridge — a cause and its effect, not two strengths of the same thing.",
      },
    ],
  },
  {
    id: "H4-20",
    family: "degree",
    stem: "SCALDING : TEPID",
    bridge: "Scalding is a stronger version of tepid.",
    gloss: "SCALDING means burning hot; TEPID means only barely warm.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "FRIGID : COOL",
        why: "Fits: frigid is a stronger version of cool — icy cold versus slightly cold.",
      },
      {
        label: "B",
        pair: "WARM : SUMMER",
        why: "Same topic, wrong bridge — a feeling and a season, no strength ladder.",
      },
      {
        label: "C",
        pair: "BOILING : STEAM",
        why: "Same topic, wrong bridge — boiling CAUSES steam; that's cause and effect.",
      },
      {
        label: "D",
        pair: "CHILLY : FREEZING",
        why: "Flipped pair — freezing is the stronger one; the order is backwards.",
      },
      {
        label: "E",
        pair: "TEMPERATURE : THERMOMETER",
        why: "Same topic, wrong bridge — a thing and the tool that measures it.",
      },
    ],
  },
  {
    id: "H4-21",
    family: "degree",
    stem: "FAMISHED : HUNGRY",
    bridge: "Famished is a stronger version of hungry.",
    gloss: "FAMISHED means so hungry you feel like you're starving.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "PARCHED : THIRSTY",
        why: "Fits: parched is a stronger version of thirsty — desperately dry versus just wanting a drink.",
      },
      {
        label: "B",
        pair: "EAT : DEVOUR",
        why: "Flipped pair — devour is the stronger one; the order is backwards.",
      },
      {
        label: "C",
        pair: "APPETITE : FOOD",
        why: "Same topic, wrong bridge — a desire and what satisfies it, no strength ladder.",
      },
      {
        label: "D",
        pair: "FULL : EMPTY",
        why: "Wrong bridge — opposites, not two strengths of the same feeling.",
      },
      {
        label: "E",
        pair: "CRUMB : LOAF",
        why: "Part instead of whole — a crumb is a tiny piece of a loaf; that's size, not intensity.",
      },
    ],
  },
  {
    id: "H4-22",
    family: "degree",
    stem: "TERROR : TREPIDATION",
    bridge: "Terror is a stronger version of trepidation.",
    gloss: "TERROR is overwhelming fear; TREPIDATION is a mild, nervous worry about what's coming.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "RAGE : IRRITATION",
        why: "Fits: rage is a stronger version of irritation — blind fury versus mild annoyance.",
      },
      {
        label: "B",
        pair: "FEAR : SCREAM",
        why: "Same topic, wrong bridge — fear CAUSES a scream; that's cause and effect.",
      },
      {
        label: "C",
        pair: "ANXIOUS : CALM",
        why: "Wrong bridge — opposites, not two strengths of the same feeling.",
      },
      {
        label: "D",
        pair: "GLUM : DESPONDENT",
        why: "Flipped pair — despondent (deeply hopeless) is the stronger one; the order is backwards.",
      },
      {
        label: "E",
        pair: "COWARD : BRAVERY",
        why: "Same topic, wrong bridge — a person and a quality they lack, no strength ladder.",
      },
    ],
  },
  {
    id: "H4-23",
    family: "degree",
    stem: "DIN : MURMUR",
    bridge: "A din is a stronger version of a murmur.",
    gloss: "A DIN is a loud, confused racket of noise; a MURMUR is a soft, low sound.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "GLARE : GLANCE",
        why: "Fits: a glare is a stronger version of a glance — a hard, angry stare versus a quick look.",
      },
      {
        label: "B",
        pair: "SILENCE : NOISE",
        why: "Wrong bridge — opposites, not two strengths of the same thing.",
      },
      {
        label: "C",
        pair: "SHOUT : MOUTH",
        why: "Same topic, wrong bridge — a sound and where it comes from, no strength ladder.",
      },
      {
        label: "D",
        pair: "TAP : POUND",
        why: "Flipped pair — pound is the stronger one; the order is backwards.",
      },
      {
        label: "E",
        pair: "ECHO : CANYON",
        why: "Same topic, wrong bridge — a sound and the place you hear it.",
      },
    ],
  },
  {
    id: "H4-24",
    family: "degree",
    stem: "DESTITUTE : POOR",
    bridge: "Destitute is a stronger version of poor.",
    gloss: "DESTITUTE means so poor you have nothing at all — no money, no home, no belongings.",
    correct: "A",
    choices: [
      {
        label: "A",
        pair: "OPULENT : WEALTHY",
        why: "Fits: opulent is a stronger version of wealthy — lavishly, showily rich versus well-off.",
      },
      {
        label: "B",
        pair: "MONEY : BANK",
        why: "Same topic, wrong bridge — a thing and the place it is kept.",
      },
      {
        label: "C",
        pair: "BEGGAR : COINS",
        why: "Same topic, wrong bridge — a person and what they ask for, no strength ladder.",
      },
      {
        label: "D",
        pair: "WEALTHY : AFFLUENT",
        why: "Too weak or too strong — these mean the SAME amount of rich; there is no step up.",
      },
      {
        label: "E",
        pair: "PROSPEROUS : BANKRUPT",
        why: "Wrong bridge — opposites, not two strengths of the same condition.",
      },
    ],
  },
];
